apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-sandbox-controller
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
rules:
{{- if not .Values.controller.watchNamespace }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - agent-sandbox-webhook-certs
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
{{- else }}
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
